# Generated by Django 2.2.15 on 2022-05-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.BigAutoField(max_length=500, primary_key=True, serialize=False)),
                ('game_id', models.BigIntegerField(max_length=500)),
                ('autor', models.CharField(max_length=30)),
                ('comentario', models.CharField(max_length=200)),
                ('nota', models.BigIntegerField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(max_length=500, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=30)),
                ('descrição', models.CharField(max_length=150)),
            ],
        ),
    ]
