# Generated by Django 2.2.15 on 2022-03-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('game_id', models.BigAutoField(max_length=500, primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=30)),
                ('game_category', models.CharField(max_length=30)),
                ('game_description', models.CharField(max_length=150)),
            ],
        ),
    ]
