# Generated by Django 2.2.15 on 2022-03-23 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='game_category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='games',
            old_name='game_description',
            new_name='descrição',
        ),
        migrations.RenameField(
            model_name='games',
            old_name='game_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='games',
            old_name='game_name',
            new_name='nome',
        ),
    ]
