# Generated by Django 4.0.4 on 2022-06-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='estado',
            field=models.CharField(default='Like', max_length=10),
        ),
    ]
